service: pco-schedule-swapper

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev

plugins:
  - serverless-plugin-include-dependencies

custom:
  sessionsTableName: ${self:service}${opt:stage, self:provider.stage}-sessionsTable

resources:
  Resources:
    SessionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.sessionsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  main:
    handler: src/server.handler
    timeout: 30
    environment:
      SESSIONS_TABLE: ${self:custom.sessionsTableName}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
